Snap: VideoModule: Restore check on mPreferenceRead
This fixes the following crash when switching from picture mode
to video mode:

FATAL EXCEPTION: main
Process: org.cyanogenmod.snap, PID: 4243
java.lang.NullPointerException: Attempt to read from field 'int android.media.CamcorderProfile.videoFrameWidth' on a null object reference
       at com.android.camera.VideoModule.updateCameraParametersInitialize(VideoModule.java:2778)
       at com.android.camera.VideoModule.setCameraParameters(VideoModule.java:2822)
       at com.android.camera.VideoModule.startPreview(VideoModule.java:1353)
       at com.android.camera.VideoModule.onPreviewUIReady(VideoModule.java:3260)
       at com.android.camera.VideoUI.surfaceCreated(VideoUI.java:956)
       at android.view.SurfaceView.updateWindow(SurfaceView.java:618)
       at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:161)
       at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:944)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2205)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6343)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
       at android.view.Choreographer.doCallbacks(Choreographer.java:686)
       at android.view.Choreographer.doFrame(Choreographer.java:621)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6126)
       at java.lang.reflect.Method.invoke(Native Method)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

Change-Id: I8f449aaa943636a9b3ce590425e8611def8df590